spring:
 resources:
  static-locations: classpath:/
 mvc:
  view:
   prefix : /templates/
   suffix : .html
   application :
    name : dream
  static-path-pattern: /resources/templates/*
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://101.132.191.175:38880/crm?useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: root
  password: root
server:
  port: 8080
  tomcat:
   max-http-post-size: 512000
logging:
  config: classpath:config/logback-config.xml
mybatis:
 mapper-locations : classpath*:mapper/base/*Mapper.xml
 type-aliases-package : com.maoju.api.domain.entity
 configuration.mapUnderscoreToCamelCase : true